### ISSUE TITLE
quality score not always the same, and which model should I use

### ISSUE THREAD

**Issue by FanglaiPeng** [pterhoer/FaceImageQuality#11]
Hi, i got 2 questions about SER-FIQ quality score when i run serfiq_example.py with 3 different model (model-r34-amf-slim, model-r50-am-lfw, model-r100-ii).
1. when one of 3 model above is specified(e.g. ,model-r50-am-lfw),  the quality score varies each time I run the code. For exampe, test_img1.jpg sometimes gets 0.551925, sometimes gets 0.549972.
2. 3 different model conduct different results. The quality score of test_img1 is always higher than test_img2 when I use model-r50-am-lfw and model-r100-ii, while test_img1 score is lower than test_img2 when model-r34-amf-slim is used. 
Is the result reasonable? And which model shoud I use? Maybe I miss something detail?

**Comment by pterhoer** [comment]
Hi FanglaiPeng,

Towards your first question: SER-FIQ determines the quality based on the embedding's robustness against dropout patterns. Since these dropout patterns randomly kick out nodes, the embedding robustness, and thus the quality predictions, slightly vary.

Regarding your second question: the aim of face images quality is to determine the utility of a face image for recognition. Utility refers to the utility for recognition. In order to determine which model you want to use, you should create error-versus-reject curves on some databases. The two test images are only there for code-testing.
If you already have a model in deployment, you can also just utilized SER-FIQ on this model. Then it will also capture the model-bias for the quality predictions. (But please note that your model should be trained with dropout to effectively use SER-FIQ )

Best
Philipp
