### ISSUE TITLE
About the threshold setting

### ISSUE THREAD

**Issue by liiiiiiiiil** [pterhoer/FaceImageQuality#14]
Hi pterhoer:
    I am confused about the threshold setting in your paper. In Section 4, it reads:"The face recognition performance is reported in terms of EER and FNMR at a FMR threshold of 0.01. The FNMR is also reported at 0.001 FMR threshold". In other papers, as I know, they set a threshold T. If the Cosine/Euclidean distance of two imgs is smaller than T, we claim it's a false match. So, is the threshold in your paper means the same? 

Thanks!
Li

**Comment by pterhoer** [comment]
Hi Li,

"The FNMR is also reported at 0.001 FMR threshold" means that report the FNMR at a fixed FMR of 0.1%. This means that when you have the ROC curve of the face recognition performance, _you choose the matching threshold such that the FMR is 0.1%_.
Having different thresholds when comparing different face recognition systems does not make sense since this will lead to a loss in comparability (different FMRs and different FNMRs).

Best
Philipp

**Comment by liiiiiiiiil** [comment]
Is that means, for example:
    I compare two face image quality assessment system by Error vs reject curves. And for each system I choose the matching threshold such that the FMR is 0.1%.  Because the performance of the two QA system is different, the threshold is different too. The threshold of system A might be 0.1, while the threshold of system B might be 0.2. Do I understand it correctly?

**Comment by liiiiiiiiil** [comment]
> Hi Li,
> 
> "The FNMR is also reported at 0.001 FMR threshold" means that report the FNMR at a fixed FMR of 0.1%. This means that when you have the ROC curve of the face recognition performance, _you choose the matching threshold such that the FMR is 0.1%_.
> Having different thresholds when comparing different face recognition systems does not make sense since this will lead to a loss in comparability (different FMRs and different FNMRs).
> 
> Best
> Philipp

Look forward to your reply

**Comment by pterhoer** [comment]
> 
> 
> Is that means, for example:
> I compare two face image quality assessment system by Error vs reject curves. And for each system I choose the matching threshold such that the FMR is 0.1%. Because the performance of the two QA system is different, the threshold is different too. The threshold of system A might be 0.1, while the threshold of system B might be 0.2. Do I understand it correctly?

Be careful, we have two different (and dynamic) thresholds in the evaluation of face quality assessement (FQA).
1. The quality threshold that filters out low quality samples and thus, determines the current test set of a FQA solution.
2. The matching threshold that determines the FMR of the face recognition (FR) system.

Both threshold might be different for different FQA and FR solutions, since they aim to "align" the performance make it comparable with other solutions.

You can find more details in the work from Grother and Tabassi (https://ieeexplore.ieee.org/document/4107559).
I will not be able to answer questions in the next two weeks, since I will be without access to the internet :)

Best
Philipp

**Comment by liiiiiiiiil** [comment]
> You can find more details in the work from Grother and Tabassi (https://ieeexplore.ieee.org/document/4107559).
> I will not be able to answer questions in the next two weeks, since I will be without access to the internet :)

Thank a lot and have a happy day
