### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by xiaoshudi** [pterhoer/FaceImageQuality#15]
Hi, I run your methods on a PC (with an Intel Core i7-4790K@4GHz, 16GB RAM and an GeForce GTX 1080) to test its runtime. I find it need about 2~3s per image. Is it a little bit longer?

**Comment by pterhoer** [comment]
Hi xiaoshudi,

as mentioned on the main page "The provided code is only a demonstration on how SER-FIQ can be utilized". It is not an optimized version. However, "our method can compensate for this issue and can easily run in real-time, since it is highly parallelizable and the computational effort can be greatly reduced by repeating the stochastic forward passes only through the last layer(s) of the network." (see paper). 

If you have further questions, let me know.

Best
Philipp
