### ISSUE TITLE
about equation 1 in paper

### ISSUE THREAD

**Issue by zackzhao1** [pterhoer/FaceImageQuality#19]
![图片](https://user-images.githubusercontent.com/28081098/92065911-33227500-edd3-11ea-8bdd-bd5af63b623f.png)
why is div m^2？maybe C(2，m)，Σ/(m(m-1)/2) as the code in this git:

    eucl_dist = euclidean_distances(norm, norm)[np.triu_indices(T, k=1)]   
    return embedding, 2*(1/(1+np.exp(np.mean(eucl_dist))))

**Comment by pterhoer** [comment]
Hi zackzhao1,

Thank you for this comment. You are right.
You can fix that in mutliple ways. One is by changing the sum to go over all pairs (sum_{i,j}).
Practically, this minor mistake will not change the performance of the quality predictions since it is a constant factor that is applied to every quality prediction :)

Best regards
Philipp
