### ISSUE TITLE
Most useless/misleading paper ever released | don't waste your time

### ISSUE THREAD

**Issue by ashuezy** [pterhoer/FaceImageQuality#38]
Everybody is expecting that this is going to return a numeric value describing the quality of the face. But this is not the case. This just checks that the vectors can handle different situations or not.

**Comment by pterhoer** [comment]
Hi ashuezy,
I am sorry that you are dissatisfied with the paper.
SER-FIQ computes the robustness of face embeddings (against dropout-variations) to estimate the face image quality.
Please note that, as we showed in the paper, this has nearly nothing to do with the general quality of the image.
Face image quality is defined over the utility of the image for recognition.
Therefore, for instance, the head position has a strong impact on the face image quality, as well as the person's demographics (due to model-bias) etc ... (https://arxiv.org/abs/2004.01019).
Best
Philipp
