### ISSUE TITLE
The model works ONLY on MTCNN aligned faces

### ISSUE THREAD

**Issue by taosean** [pterhoer/FaceImageQuality#45]
Hi, Thanks for your work!

I found an interesting thing about the SER-FIQ model.
I used `data/test_img.jpeg` for testing.

First, I cropped the output of [this line](https://github.com/pterhoer/FaceImageQuality/blob/4e8da2ca65fe6dfe71a3c6fddde9a3d1ba8c205c/face_image_quality.py#L116) and saved it as a jpg file, naming `1.jpg`
![test_img_3](https://user-images.githubusercontent.com/17960909/149730192-d2a4f97f-ab1d-48be-9750-b5194193a7bd.jpg)

Second, I used ffmpeg command `ffmpeg -i 1.jpg -q:v 10 2.jpg` to decrease the quality of the image, and save it as `2.jpg`
![test_img_4](https://user-images.githubusercontent.com/17960909/149730600-518bf79c-a5c5-4e93-bb0b-0dc0c0302c03.jpg)

Third, I used my own face detection model (UltraFace) and landmark detection model (FAN model) to detect and align the face and saved the face image as `3.jpg`.
![test_img_face](https://user-images.githubusercontent.com/17960909/149731729-cd47446b-ae65-4e3c-94b1-4bab2ab965b5.jpg)

Fourth, I test the three images with SER-FIQ model with the following code 
```python
    ser_fiq = SER_FIQ(gpu=1)

    test_img_folder = './data'

    face_imgs = glob.glob(os.path.join(test_img_folder, '*.jpg'))
    for face_img in face_imgs:
        test_img_ori = cv2.imread(face_img)
        test_img = cv2.cvtColor(test_img_ori, cv2.COLOR_BGR2RGB)
        aligned_img = np.transpose(test_img, (2, 0, 1))

        score = ser_fiq.get_score(aligned_img, T=100)
        new_path = os.path.join('outputs', str(score)+ '_' + os.path.basename(face_img))

        cv2.imwrite(new_path, test_img_ori)

        print("SER-FIQ quality score of image is", score)
```

And the results are:
```
1.jpg: 0.8465793745298666
2.jpg: 0.8412792795675421
3.jpg: 0.05755140244918808
```

As you can see, the SER-FIQ model is robust to the image quality (or image size) decreasing, however, when facing images aligned from other models (not MTCNN), the score decreases dramatically.

Have you encountered this problem and do you know why this happen?

Thanks!

**Comment by jankolf** [comment]
Hi @taosean 
thanks for your questions. The SER-FIQ method basically indicates how well a network can handle an input. This includes how often the network has seen a type of input during training. If a certain alignment method was used for training, the network can only produce safe embeddings with this alignment, other alignment methods like the one used in Figure 3, where the face takes up much more space in the image, therefore work worse than the original MTCNN, because these kinds of face images did not appear in the training data.
The ability to handle different image quality depends on the training process and the dataset used.
I hope this answers your questions.

Kind regards,
Jan

**Comment by taosean** [comment]
Hi, @jankolf , thank you for your reply.

I understand your point.

Thanks.
